export const allCars = [
  "Skoda Fabia R5 evo",
  "Subaru Impreza GC8 555 GrpA",
  "Hyundai i20 N Rally2",
  "Ford Fiesta Rally3",
  "Peugeot 208 Rally4",
  "Toyota Yaris WRC 2018",
  "Peugeot 106 Rallye S20 GrpA",
  "VW Polo GTI R5",
  "Hyundai i20 Coupe WRC 2021",
  "Mitsubishi Lancer Evo IX R4",
  "Citroen C3 R5",
  "Ford Fiesta Rally2",
  "Renault Clio 16S Williams GrpA",
  "BMW M3 E30 GrpA",
  "Ford Escort Mk II RS Grp4",
  "Hyundai i20 R5",
  "Ford Fiesta WRC 2019",
  "Peugeot 208 R2",
  "Subaru Impreza GDA WRC2003 (S9)",
  "Mitsubishi Lancer Evo X R4",
  "Fiat 131 Abarth Grp4",
  "Peugeot 306 Maxi Kit Car",
  "Peugeot 208 T16 R5",
  "Skoda Fabia R5",
  "BMW M3 E36 GrpA",
  "Skoda 130 RS Grp2",
  "Skoda Favorit 136 L GrpA",
  "Lada VFTS GrpB",
  "VW Golf II GTI 16V GrpA",
  "Porsche 911 SC 3.0 Grp4",
  "Hyundai i20 Coupe WRC 2020",
  "Ford Escort Mk V RS Cosworth Grp",
  "Ford Fiesta R5",
  "Renault Clio Rally4",
  "Skoda Fabia WRC 2006",
  "Citroen DS3 WRC",
  "Toyota Celica 2000GT(ST185) GrpA",
  "Mitsubishi Lancer Evo IX N4",
  "Mitsubishi Lancer Evo II GrpA",
  "Audi Sport quattro GrpB",
  "Citroen C2 R2 Max",
  "Lancia Delta HF 4WD GrpA",
  "Opel Ascona 400 Grp4",
  "Peugeot 207 S2000 Evolution Plus",
  "Ford Fiesta Rally4",
  "Audi 200 quattro GrpA",
  "Volvo 240 Turbo GrpA",
  "Citroen C3 WRC 2017",
  "Subaru Impreza N15 R4",
  "Lancia Stratos HF Grp4",
  "Audi quattro Grp4",
  "Skoda Fabia S2000 Evo 2",
  "Hyundai i20 Coupe WRC 2017",
  "Wartburg 353 W 460 GrpA",
  "Porsche 911 GT3 RS (2010) RGT",
  "Opel ADAM R2",
  "Citroen Xsara Kit Car",
  "Opel Manta 400 GrpB",
  "Renault Clio III R3",
  "Citroen C2 GT S1600",
  "Renault Twingo R2 Evo",
  "Ford Focus Mk II RS WRC 2006",
  "Ford Fiesta RS WRC 2014",
  "Peugeot 205 T16 GrpB",
  "Fiat 126 Grp2",
  "VW Polo R WRC 2016",
  "Porsche 911 SC RS GrpB",
  "Mazda 323 BF 4WD Turbo GrpA",
  "Renault Clio Rally5",
  "Ford Fiesta R2",
  "Ford Fiesta Mk VI S2000",
  "Citroen C4 WRC 2008",
  "Citroen DS3 R5",
  "Mini JCW WRC",
  "Trabant P 800 RS GrpA",
  "Honda Civic Type R(FN2) R3",
  "Renault 5 GT Turbo GrpA",
  "Citroen Xsara WRC 2006",
  "Citroen DS3 R1",
  "Audi quattro A2 GrpB",
  "Aston Martin Vantage RGT",
  "Ford Fiesta Mk VIII R2",
  "Toyota Celica TCT (TA64) GrpB",
  "Subaru Impreza N14 N4",
  "Renault Clio IV R3T",
  "Abarth Grande Punto S2000",
  "Skoda 130 LR GrpB",
  "Alpine A110 Rally RGT",
  "Renault Twingo R1",
  "Lada Kalina RC2 GrpA",
  "Citroen DS3 R3-MAX",
  "BMW M1 GrpB",
  "Porsche 911 GT3 RS (2007) RGT",
  "Fiat Abarth 500 R3T",
  "Audi quattro A1 GrpB",
  "Fiat 124 Abarth Rally RGT",
  "Lotus Exige S RGT",
  "Seat Leon Cupra R GrpN",
];

export const carsByGroup = {
  "WRC 1.6": [
    "Toyota Yaris WRC 2018",
    "Hyundai i20 Coupe WRC 2021",
    "Ford Fiesta WRC 2019",
    "Hyundai i20 Coupe WRC 2020",
    "Citroen DS3 WRC",
    "Citroen C3 WRC 2017",
    "Hyundai i20 Coupe WRC 2017",
    "Ford Fiesta RS WRC 2014",
    "VW Polo R WRC 2016",
    "Mini JCW WRC",
  ],
  "WRC 2.0": [
    "Subaru Impreza GDA WRC2003 (S9)",
    "Skoda Fabia WRC 2006",
    "Ford Focus Mk II RS WRC 2006",
    "Citroen C4 WRC 2008",
    "Citroen Xsara WRC 2006",
  ],
  "Group 2": ["Skoda 130 RS Grp2", "Fiat 126 Grp2"],
  "Group 4": [
    "Ford Escort Mk II RS Grp4",
    "Fiat 131 Abarth Grp4",
    "Porsche 911 SC 3.0 Grp4",
    "Opel Ascona 400 Grp4",
    "Lancia Stratos HF Grp4",
    "Audi quattro Grp4",
  ],
  "Group A5": [
    "Skoda Favorit 136 L GrpA",
    "Wartburg 353 W 460 GrpA",
    "Trabant P 800 RS GrpA",
  ],
  "Group A6": ["Peugeot 106 Rallye S20 GrpA", "Lada Kalina RC2 GrpA"],
  "Group A7": [
    "Renault Clio 16S Williams GrpA",
    "Peugeot 306 Maxi Kit Car",
    "VW Golf II GTI 16V GrpA",
    "Citroen Xsara Kit Car",
    "Renault 5 GT Turbo GrpA",
  ],
  "Group A8": [
    "Subaru Impreza GC8 555 GrpA",
    "BMW M3 E30 GrpA",
    "BMW M3 E36 GrpA",
    "Ford Escort Mk V RS Cosworth Grp",
    "Toyota Celica 2000GT(ST185) GrpA",
    "Mitsubishi Lancer Evo II GrpA",
    "Lancia Delta HF 4WD GrpA",
    "Audi 200 quattro GrpA",
    "Volvo 240 Turbo GrpA",
    "Mazda 323 BF 4WD Turbo GrpA",
  ],
  "Group B": [
    "Lada VFTS GrpB",
    "Audi Sport quattro GrpB",
    "Opel Manta 400 GrpB",
    "Peugeot 205 T16 GrpB",
    "Porsche 911 SC RS GrpB",
    "Audi quattro A2 GrpB",
    "Toyota Celica TCT (TA64) GrpB",
    "Skoda 130 LR GrpB",
    "BMW M1 GrpB",
    "Audi quattro A1 GrpB",
  ],
  "Group N4": [
    "Mitsubishi Lancer Evo IX N4",
    "Subaru Impreza N14 N4",
    "Seat Leon Cupra R GrpN",
  ],
  "Group R1": ["Citroen DS3 R1", "Renault Twingo R1"],
  "Group R2": [
    "Peugeot 208 R2",
    "Citroen C2 R2 Max",
    "Opel ADAM R2",
    "Renault Twingo R2 Evo",
    "Ford Fiesta R2",
    "Ford Fiesta Mk VIII R2",
  ],
  "Group R3": [
    "Renault Clio III R3",
    "Honda Civic Type R(FN2) R3",
    "Renault Clio IV R3T",
    "Citroen DS3 R3-MAX",
    "Fiat Abarth 500 R3T",
  ],
  "Group R4": [
    "Mitsubishi Lancer Evo IX R4",
    "Mitsubishi Lancer Evo X R4",
    "Subaru Impreza N15 R4",
  ],
  "Group R5": [
    "Skoda Fabia R5 evo",
    "VW Polo GTI R5",
    "Citroen C3 R5",
    "Hyundai i20 R5",
    "Peugeot 208 T16 R5",
    "Skoda Fabia R5",
    "Ford Fiesta R5",
    "Citroen DS3 R5",
  ],
  "Group RGT": [
    "Porsche 911 GT3 RS (2010) RGT",
    "Aston Martin Vantage RGT",
    "Alpine A110 Rally RGT",
    "Porsche 911 GT3 RS (2007) RGT",
    "Fiat 124 Abarth Rally RGT",
    "Lotus Exige S RGT",
  ],
  "Super 1600": ["Citroen C2 GT S1600"],
  "Super 2000": [
    "Peugeot 207 S2000 Evolution Plus",
    "Skoda Fabia S2000 Evo 2",
    "Ford Fiesta Mk VI S2000",
    "Abarth Grande Punto S2000",
  ],
  "Rally 5": ["Renault Clio Rally5"],
  "Rally 4": [
    "Peugeot 208 Rally4",
    "Renault Clio Rally4",
    "Ford Fiesta Rally4",
  ],
  "Rally 3": ["Ford Fiesta Rally3"],
  "Rally 2": ["Hyundai i20 N Rally2", "Ford Fiesta Rally2"],
};
